### ISSUE TITLE
Error with SecQuery::Filing.recent()

### ISSUE THREAD

**Issue by maxiedaniels** [tyrauber/sec_query#42]
I'm trying to use `SecQuery::Filing.recent(start: 0, count: 10, limit: 10)` but I'm getting an error:

```
undefined method `call' for nil:NilClass (NoMethodError)
	from /Users/user/.rvm/gems/ruby-2.4.0/gems/sec_query-1.3.0/lib/sec_query/filing.rb:114:in `each'
	from /Users/user/.rvm/gems/ruby-2.4.0/gems/sec_query-1.3.0/lib/sec_query/filing.rb:114:in `parse_rss'
	from /Users/user/.rvm/gems/ruby-2.4.0/gems/sec_query-1.3.0/lib/sec_query/filing.rb:19:in `block in fetch'
	from /Users/user/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/open-uri.rb:155:in `open_uri'
	from /Users/user/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/open-uri.rb:721:in `open'
	from /Users/user/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/open-uri.rb:35:in `open'
	from /Users/user/.rvm/gems/ruby-2.4.0/gems/sec_query-1.3.0/lib/sec_query/filing.rb:18:in `fetch'
	from /Users/user/.rvm/gems/ruby-2.4.0/gems/sec_query-1.3.0/lib/sec_query/filing.rb:28:in `recent'
```

Any ideas?

**Comment by tyrauber** [comment]
Hi @maxiedaniels, it looks like the documentation is incorrect. 

Filing.recent apparently requires a block:
```
filings = []
SecQuery::Filing.recent(start: 0, count: 10, limit: 10) do |filing|
  filings.push filing
end
```
Thanks for bringing this to my attention. I'll update the documentation.
